FROM itzg/minecraft-server:java21

ENV EULA=TRUE \
    TYPE=FABRIC \
    VERSION=1.16.1 \
    ONLINE_MODE=FALSE \
    MEMORY=2G \
    DIFFICULTY=hard \
    SPAWN_PROTECTION=0 \
    ENABLE_COMMAND_BLOCK=TRUE

COPY mcsrswap-fabric-mod-*.jar /mods/

EXPOSE 25565

VOLUME ["/data"]
